"""
tests/test_host_helper_models.py — Smoke tests for host helper model endpoints.

Run manually on Windows host (where lmm_host_helper.py runs):
    python tests/test_host_helper_models.py --host localhost --port 55501

Requires:
    - lmm_host_helper.py running on the host
    - Token available at %TEMP%/a0_lmm_host.key (auto-generated by helper)
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path


def _read_token() -> str:
    temp = os.environ.get("TEMP", os.environ.get("TMP", tempfile.gettempdir()))
    token_path = Path(temp) / "a0_lmm_host.key"
    try:
        return token_path.read_text(encoding="utf-8").strip()
    except Exception:
        return ""


def _request(host: str, port: int, method: str, path: str, body: dict | None = None) -> dict:
    url = f"http://{host}:{port}{path}"
    data = json.dumps(body).encode("utf-8") if body else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Content-Type", "application/json")
    req.add_header("X-Token", _read_token())
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        try:
            return json.loads(e.read().decode("utf-8"))
        except Exception:
            return {"ok": False, "error": f"HTTP {e.code}"}
    except Exception as e:
        return {"ok": False, "error": str(e)}


def test_health(host: str, port: int) -> bool:
    """Test public health endpoint (no token required)."""
    url = f"http://{host}:{port}/health"
    try:
        req = urllib.request.Request(url, method="GET")
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            if data.get("ok") and data.get("service") == "lmm_host_helper":
                print("[PASS] /health — service is up")
                return True
    except Exception as e:
        print(f"[FAIL] /health — {e}")
        return False
    return False


def test_list_models(host: str, port: int) -> bool:
    """Test /models/list endpoint."""
    r = _request(host, port, "GET", "/models/list")
    if r.get("ok") and "models" in r:
        count = len(r.get("models", {}))
        print(f"[PASS] /models/list — returned {count} models")
        return True
    print(f"[FAIL] /models/list — {r.get('error', 'unknown')}")
    return False


def test_hf_token(host: str, port: int) -> bool:
    """Test /tokens/hf GET and POST."""
    # Check status
    r = _request(host, port, "GET", "/tokens/hf")
    if not r.get("ok"):
        print(f"[FAIL] GET /tokens/hf — {r.get('error')}")
        return False
    print(f"[PASS] GET /tokens/hf — has_token={r.get('has_token')}")

    # Set a test token
    r = _request(host, port, "POST", "/tokens/hf", {"token": "hf_test_token_12345"})
    if not r.get("ok"):
        print(f"[FAIL] POST /tokens/hf — {r.get('error')}")
        return False
    print("[PASS] POST /tokens/hf — token set")

    # Verify it was set
    r = _request(host, port, "GET", "/tokens/hf")
    if r.get("has_token"):
        print("[PASS] GET /tokens/hf — token persisted")
    else:
        print("[WARN] GET /tokens/hf — token did not persist (may be expected)")

    # Clear token
    r = _request(host, port, "DELETE", "/tokens/hf")
    if not r.get("ok"):
        print(f"[FAIL] DELETE /tokens/hf — {r.get('error')}")
        return False
    print("[PASS] DELETE /tokens/hf — token cleared")
    return True


def test_job_status_not_found(host: str, port: int) -> bool:
    """Test /models/jobs/{id} with non-existent job."""
    r = _request(host, port, "GET", "/models/jobs/nonexistent_job_12345")
    if r.get("status") == "unknown":
        print("[PASS] /models/jobs/{id} — returns 'unknown' for non-existent job")
        return True
    print(f"[FAIL] /models/jobs/{{id}} — unexpected response: {r}")
    return False


def test_assign_invalid_slot(host: str, port: int) -> bool:
    """Test /models/assign with invalid slot name."""
    r = _request(host, port, "POST", "/models/assign", {
        "slot": "invalid_slot_name",
        "model_id": "some_model",
        "apply_now": False,
    })
    if not r.get("ok") and "invalid slot" in (r.get("error") or "").lower():
        print("[PASS] /models/assign — rejects invalid slot")
        return True
    if not r.get("ok"):
        print(f"[PASS] /models/assign — rejected (error: {r.get('error')})")
        return True
    print(f"[WARN] /models/assign — unexpected success for invalid slot: {r}")
    return True  # Soft pass


def test_assign_missing_model(host: str, port: int) -> bool:
    """Test /models/assign with non-existent model."""
    r = _request(host, port, "POST", "/models/assign", {
        "slot": "chat",
        "model_id": "nonexistent_model_xyz",
        "apply_now": False,
    })
    if not r.get("ok") and "not found" in (r.get("error") or "").lower():
        print("[PASS] /models/assign — rejects non-existent model")
        return True
    if not r.get("ok"):
        print(f"[PASS] /models/assign — rejected (error: {r.get('error')})")
        return True
    print(f"[WARN] /models/assign — unexpected success for missing model: {r}")
    return True  # Soft pass


def main() -> int:
    parser = argparse.ArgumentParser(description="Smoke tests for lmm_host_helper model endpoints")
    parser.add_argument("--host", default="localhost", help="Host helper hostname")
    parser.add_argument("--port", type=int, default=55501, help="Host helper port")
    args = parser.parse_args()

    print(f"Testing lmm_host_helper at {args.host}:{args.port}")
    print(f"Token path: {Path(tempfile.gettempdir()) / 'a0_lmm_host.key'}")
    print("-" * 50)

    results = []
    tests = [
        test_health,
        test_list_models,
        test_hf_token,
        test_job_status_not_found,
        test_assign_invalid_slot,
        test_assign_missing_model,
    ]

    for test in tests:
        try:
            results.append(test(args.host, args.port))
        except Exception as e:
            print(f"[EXCEPTION] {test.__name__} — {e}")
            results.append(False)
        print()

    passed = sum(results)
    total = len(results)
    print("-" * 50)
    print(f"Results: {passed}/{total} passed")
    return 0 if passed == total else 1


if __name__ == "__main__":
    sys.exit(main())
